name: CI/CD - Deploy Streamlit to Azure

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry (ACR)
        run: az acr login --name acrmlopsdemoiris

      - name: Build and Push Docker Image to ACR
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            acrmlopsdemoiris.azurecr.io/streamlit:${{ github.sha }}
            acrmlopsdemoiris.azurecr.io/streamlit:latest
          file: Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_STREAMLIT }}
          slot-name: "production"
          images: acrmlopsdemoiris.azurecr.io/streamlit:latest
